### ISSUE TITLE
Collection dashboards - can we show capitalised collector names

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#36]
This is based on some feedback I received.
In the collection dashboard, we show the number of occurrences per collector: https://scientific-collections.gbif.org/collection/fbd7320b-79c4-476c-807d-c006927ab6a6/dashboard.
In the bar chart, the names aren't capitalised: `robert g. webb` even though they are in the occurrences:
<img width="675" alt="Screenshot 2023-10-12 at 14 46 17" src="https://github.com/gbif/hp-grscicoll/assets/7677271/a988a8cb-f6c7-47dd-9e8b-81e89f80fb7c">
Could we have the same capitalisation in the dashboard?

Feel free to move to a different repository. I wasn't sure where to log it.

**Comment by MortenHofft** [comment]
Not really no. I do not think we can do that. They are lower cased in the index. I could try to guess the correct casing, but the original casing is lost to my knowledge. @fmendezh you might now if there is an option to do so that I have missed. It is simply a facet on recordedBy similar to apiv1 https://api.gbif.org/v1/occurrence/search?facet=recordedBy&limit=0

Unless Federico knows how to change this, then my best guess is to capitalise each word. But that will surely be wrong in some cases, but it might be overall better. The only other altrenative I can come up with is to fetch one example record per row and use that value. But even that might be wrong. The reason we lower case them all to begin with is to group case variations into one bucket. So `TS Eliot` and `Ts Eliot` will count as the same name. 

But if they control the data, then it would be nice to clean other parts. Such as the recordedBy: `Collector(s):...`. That looks odd to me. Like saying `basisOfRecord: "Basis of record: preservedSpecimen"` And otherCatalogueNumbers look odd as well.

**Comment by MortenHofft** [comment]
rewriting to title case will in many situations just be more annoying and confusing i fear.

Example value: `collector(s): t.s. eliot;danny devito; john d'angleterre`
Ought to be: `Collector(s): T.S. Eliot;Danny DeVito; John d'Angleterre`

lodash lib would turn that into `"Collector S T S Eliot Danny Devito John Dangleterre"`
Other lib gives me `Collector(S): T.S. Eliot;danny Devito; John D'angleterre`. 

It would probably serve us better to try to reuse the actual values, than try to reconstruct it based in guessing

**Comment by MortenHofft** [comment]
I've implemented the version that do an occurrence search per facet result and then takes the first result, and then filters that by lowerCase matching.
So e.g.
We do a facet of recordedBy. That returns 10 names, e.g. `danny devito`.
Then I do an occurrence search with `recordedBy=danny devito & limit=1`
That result will have a recordedBy field as an array like `recordedBy= ["Danny DeVito", "Johnny depp", "danny Devito"]`
It will then filter that list and take the **first** record that when lower cased equals `danny devito`.

If there are more than one occurrence search result, which might have different casing, then those results are ignored.

All of that is just to explain: that this might *still* provide the wrong casing in some edge cases. But it will likely be correct the vast majority of the time. I haven't bothered quantifying how often it will be wrong

**Comment by ManonGros** [comment]
Thanks @MortenHofft! This is wonderful! <3

I assume, when can I make a release? (I assume not today, let me know, thanks!)

**Comment by MortenHofft** [comment]
You can make releases when you need to. But you making a release is unrelated to this. The site is updated when i deploy the code. And I already did that.
